# Generated by Django 3.2.6 on 2021-09-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210927_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='title',
            new_name='name',
        ),
    ]
