# Generated by Django 3.2.6 on 2021-09-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_title_listings_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='image_url',
            new_name='image',
        ),
    ]
