# Generated by Django 3.2.6 on 2021-09-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_image_url_listings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='isclosed',
            new_name='is_closed',
        ),
    ]
