# Generated by Django 3.2.6 on 2021-09-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_isclosed_listings_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='iswatching',
            new_name='is_watching',
        ),
        migrations.AlterField(
            model_name='listings',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='all_categories', to='auctions.Categories'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_category', to='auctions.categories'),
        ),
    ]
